In [7]:
import numpy as np

print(np.__version__)

1.14.2


In [15]:
a = np.arange(6)
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print (a)

[1 2 3 4 5 6]
[0 1 2 3 4 5]


In [16]:
numpy_array = np.array([1,8,5,59,8,98], dtype = 'float')
print(numpy_array)

[ 1.  8.  5. 59.  8. 98.]


In [17]:
# let's try Numpy array with string as input
str = ['the','air','after','summer','rain']
arr = np.array(str, dtype = 'str')
print(arr)

['the' 'air' 'after' 'summer' 'rain']


In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [36]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
print(2*"") 
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"
print(2*"") 
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
print(2*"")          #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
print(2*"")         #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
print(2*"")                 #               [ 0.68744134  0.87236687]]"

d = np.diag(np.array([1, 2, 3, 4]))
print(d)
print(2*"")

a = np.diag(np.arange(3))
print(a)

[[0. 0.]
 [0. 0.]]

[[1. 1.]]

[[7 7]
 [7 7]]

[[1. 0.]
 [0. 1.]]

[[0.03505751 0.46818881]
 [0.87614944 0.79245646]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

2


In [ ]:
# Python program to demonstrate 
# basic array characteristics
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

In [ ]:
c = np.linspace(0, 1, 6)   # start, end, num-points

# Higher Dimensional Arrays

In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
